# Generated by Django 2.1 on 2018-08-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation',
            new_name='amount',
        ),
    ]
