# Generated by Django 2.1 on 2018-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0002_auto_20180830_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
